/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Report;

import ORM.Booking;
import ORM.Photographer;
import ORM_Controller.Photographer_Controller;
import java.util.ArrayList;
import java.util.Date;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author El Gato
 */
public class PhotographerAvailability extends javax.swing.JFrame {
    private DefaultTableModel schedules;
    private DefaultComboBoxModel photographers;
    private ArrayList<Date> date;
    
    private ArrayList<Photographer> photographer_list;
    private ArrayList<Booking> booking_list_PP;
    private ArrayList<Booking> booking_list_AP;
    
    private TreeMap<Integer,Integer> hiredHours;
    private TreeMap<String,String> vacantHours;
    /**
     * Creates new form PhotographerSchedule
     */
    public PhotographerAvailability() {
        schedules = new DefaultTableModel();
        
        hiredHours = new TreeMap<>();
        vacantHours = new TreeMap<>();
        //photographers = new DefaultComboBoxModel();
        
        setPhotographerList();
        
        schedules.addColumn("Time in");
        schedules.addColumn("Time out");
        
        
        initComponents();
    }

    
    private void setPhotographerList(){
        photographer_list = new ArrayList<>(new Photographer_Controller().viewAllPhotographers());
        System.out.println(photographer_list);
        photographers = new DefaultComboBoxModel(photographer_list.toArray());
    }
    
    private void viewPhotographerSchedule(Integer _month, Integer _year, Integer _day, Photographer _p){
        
        booking_list_PP = new ArrayList<>(_p.getBookingCollection1());
        booking_list_AP = new ArrayList<>(_p.getBookingCollection());
             String start = "0";
            String end = "23";
        
        
        for(Booking tuple: booking_list_PP){
       
            if(_month.equals(tuple.getSDate().getMonth()) && 
                    _year.equals(tuple.getSDate().getYear()) &&
                    _day.equals(tuple.getSDate().getDate()))
            {
                hiredHours.put(tuple.getTimeIn(),tuple.getTimeOut());
            }
        }    
        for(Booking tuple: booking_list_AP){
       
            if(_month.equals(tuple.getSDate().getMonth()) && 
                    _year.equals(tuple.getSDate().getYear()) &&
                    _day.equals(tuple.getSDate().getDate()))
            {
                hiredHours.put(tuple.getTimeIn(),tuple.getTimeOut());
            }
        }    
             for (Map.Entry<Integer, Integer> entry : hiredHours.entrySet()) {
                    System.out.println(start);
                    String timestart = String.valueOf(entry.getKey());
                    String timeend = String.valueOf(entry.getValue());
                    System.out.println(timestart);
                    if (!start.equals(timestart)) {
                        vacantHours.put(start, timestart);
                    }
                    start=timeend;
                }
                if (!start.equals(end)) {
                    vacantHours.put(start, end);
                }
                for (Map.Entry<String, String> entry : vacantHours.entrySet()) {

                    Object[] o = {entry.getKey(), entry.getValue()};
                    schedules.addRow(o);
                }
                table.setModel(schedules);
        
        
        
        
        
        //------------------------------------------------------------------

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Month = new javax.swing.JComboBox();
        PhotographerList = new javax.swing.JComboBox();
        View = new javax.swing.JButton();
        Year = new javax.swing.JComboBox();
        Day = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ribbon", 0, 14)); // NOI18N
        jLabel1.setText("Photographer:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 30));

        jLabel2.setFont(new java.awt.Font("Ribbon", 0, 14)); // NOI18N
        jLabel2.setText("Select Date:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        Month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        getContentPane().add(Month, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 90, -1));

        PhotographerList.setModel(photographers);
        PhotographerList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhotographerListActionPerformed(evt);
            }
        });
        getContentPane().add(PhotographerList, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 270, 30));

        View.setText("View");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });
        getContentPane().add(View, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, -1, -1));

        Year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        getContentPane().add(Year, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        Day.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(Day, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        table.setModel(schedules);
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, 180));

        jLabel3.setFont(new java.awt.Font("Homestead Regular", 0, 18)); // NOI18N
        jLabel3.setText("PHOTOGRAPHER AVAILABILITY");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PhotographerListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhotographerListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhotographerListActionPerformed

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        // TODO add your handling code here:
        schedules.setRowCount(0);
        hiredHours.clear();
        vacantHours.clear();
        table.setModel(schedules);
        Photographer instance = photographer_list.get(PhotographerList.getSelectedIndex());
        //date = instance.get
        //yy - 1900 , mm , dd
        //Integer year = Integer.valueOf(String.valueOf(Month));
        Integer year = Integer.valueOf(String.valueOf(Year.getSelectedItem())) - 1900;
        Integer month = Month.getSelectedIndex();
        Integer day = Day.getSelectedIndex()+1;
        //Integer date 
        System.out.println("by: " + instance);
        System.out.println("month" + month);
        System.out.println("year" + year);
        
        
        viewPhotographerSchedule(month, year, day, instance);
        
    }//GEN-LAST:event_ViewActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Day;
    private javax.swing.JComboBox Month;
    private javax.swing.JComboBox PhotographerList;
    private javax.swing.JButton View;
    private javax.swing.JComboBox Year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
