/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Booking;

/**
 *
 * @author user
 */
public class BookMenu extends javax.swing.JFrame {

    /**
     * Creates new form choicePane
     */
    public BookMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPane = new javax.swing.JPanel();
        Label = new javax.swing.JLabel();
        Label1 = new javax.swing.JLabel();
        new_Button = new javax.swing.JButton();
        notNew_Button = new javax.swing.JButton();
        bg_choicePane = new javax.swing.JLabel();

        mainPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label.setBackground(new java.awt.Color(255, 255, 102));
        Label.setFont(new java.awt.Font("Homestead Display", 0, 36)); // NOI18N
        Label.setForeground(new java.awt.Color(255, 255, 51));
        Label.setText("to Liz' photostudio?");
        mainPane.add(Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 410, 90));

        Label1.setBackground(new java.awt.Color(255, 255, 102));
        Label1.setFont(new java.awt.Font("Homestead Display", 0, 36)); // NOI18N
        Label1.setForeground(new java.awt.Color(255, 255, 51));
        Label1.setText("Are you new");
        mainPane.add(Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 270, 90));

        new_Button.setFont(new java.awt.Font("Ribbon", 0, 80)); // NOI18N
        new_Button.setForeground(new java.awt.Color(255, 51, 153));
        new_Button.setText("No");
        new_Button.setContentAreaFilled(false);
        new_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_ButtonActionPerformed(evt);
            }
        });
        mainPane.add(new_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 200, 170));

        notNew_Button.setFont(new java.awt.Font("Ribbon", 0, 80)); // NOI18N
        notNew_Button.setForeground(new java.awt.Color(0, 255, 255));
        notNew_Button.setText("YES");
        notNew_Button.setContentAreaFilled(false);
        notNew_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notNew_ButtonActionPerformed(evt);
            }
        });
        mainPane.add(notNew_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 200, 170));

        bg_choicePane.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/bbbb.jpg"))); // NOI18N
        mainPane.add(bg_choicePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void new_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_ButtonActionPerformed

    private void notNew_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notNew_ButtonActionPerformed
  
    }//GEN-LAST:event_notNew_ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel bg_choicePane;
    private javax.swing.JPanel mainPane;
    private javax.swing.JButton new_Button;
    private javax.swing.JButton notNew_Button;
    // End of variables declaration//GEN-END:variables
}
