/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;


import Client.EditClient;
import Photographer.EditPhotographer;
import Photographer.addPhotographer_Frame;
import Photographer.removePhotographer;
import Report.Report_Menu;
import Report.PhotographerAvailability;
import Service.ViewServices;


/**
 *
 * @author user
 */
public class MainPane extends javax.swing.JFrame {

    /**
     * Creates new form MainPane
     */
    public MainPane() {
        initComponents();
        adminPane.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        addPhotoshoot_Frame = new javax.swing.JFrame();
        clientInfo = new javax.swing.JPanel();
        name_Label1 = new javax.swing.JLabel();
        name_Input1 = new javax.swing.JTextField();
        contactNumber_Label1 = new javax.swing.JLabel();
        contactNumber_Input1 = new javax.swing.JTextField();
        emailAddress_Label1 = new javax.swing.JLabel();
        emailAddress_Input1 = new javax.swing.JTextField();
        name_Label2 = new javax.swing.JLabel();
        name_Input2 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        bookingInfo = new javax.swing.JPanel();
        whereChoice_Pane = new javax.swing.JPanel();
        emailAddress_Label2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        studio_Choice = new javax.swing.JPanel();
        emailAddress_Label4 = new javax.swing.JLabel();
        addPG_Buttons1 = new javax.swing.JPanel();
        cancelP_Button1 = new javax.swing.JButton();
        confirmP_Button1 = new javax.swing.JButton();
        resetP_Button1 = new javax.swing.JButton();
        adminPane = new javax.swing.JPanel();
        title2 = new javax.swing.JLabel();
        addPhotoGrapher_Button = new javax.swing.JButton();
        editPhotoGrapher_Button1 = new javax.swing.JButton();
        removePG_Button = new javax.swing.JButton();
        ViewPhotographerSchedule = new javax.swing.JButton();
        toGuest_Button = new javax.swing.JButton();
        Services_Button = new javax.swing.JButton();
        Clients = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        clientPane = new javax.swing.JPanel();
        title3 = new javax.swing.JLabel();
        bookButton = new javax.swing.JButton();
        toAdminButton = new javax.swing.JButton();
        checkPhotoGButton = new javax.swing.JButton();
        viewBrochureButton = new javax.swing.JButton();
        background1 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Input Photographer's");

        jButton3.setText("Remove");

        jButton4.setText("Cancel");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        addPhotoshoot_Frame.setAlwaysOnTop(true);
        addPhotoshoot_Frame.setMinimumSize(new java.awt.Dimension(390, 500));
        addPhotoshoot_Frame.setResizable(false);

        clientInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Client Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Homestead Display", 0, 24))); // NOI18N

        name_Label1.setFont(new java.awt.Font("Ribbon", 0, 18)); // NOI18N
        name_Label1.setText("First Name");

        name_Input1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        contactNumber_Label1.setFont(new java.awt.Font("Ribbon", 0, 18)); // NOI18N
        contactNumber_Label1.setText("Contact Number");

        contactNumber_Input1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        emailAddress_Label1.setFont(new java.awt.Font("Ribbon", 0, 18)); // NOI18N
        emailAddress_Label1.setText("Email Address");

        emailAddress_Input1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        name_Label2.setFont(new java.awt.Font("Ribbon", 0, 18)); // NOI18N
        name_Label2.setText("Last Name");

        name_Input2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jRadioButton1.setFont(new java.awt.Font("Ribbon", 0, 14)); // NOI18N
        jRadioButton1.setText("Family");

        jRadioButton2.setFont(new java.awt.Font("Ribbon", 0, 14)); // NOI18N
        jRadioButton2.setText("Individual");

        jRadioButton3.setFont(new java.awt.Font("Ribbon", 0, 14)); // NOI18N
        jRadioButton3.setText("Company / Corporation");

        javax.swing.GroupLayout clientInfoLayout = new javax.swing.GroupLayout(clientInfo);
        clientInfo.setLayout(clientInfoLayout);
        clientInfoLayout.setHorizontalGroup(
            clientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clientInfoLayout.createSequentialGroup()
                        .addComponent(name_Label1)
                        .addGap(18, 18, 18)
                        .addComponent(name_Input1))
                    .addGroup(clientInfoLayout.createSequentialGroup()
                        .addComponent(name_Label2)
                        .addGap(18, 18, 18)
                        .addComponent(name_Input2))
                    .addGroup(clientInfoLayout.createSequentialGroup()
                        .addGroup(clientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(contactNumber_Label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailAddress_Label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailAddress_Input1)
                            .addComponent(contactNumber_Input1)))
                    .addGroup(clientInfoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        clientInfoLayout.setVerticalGroup(
            clientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(name_Label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(name_Input1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(name_Label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(name_Input2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contactNumber_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactNumber_Input1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailAddress_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailAddress_Input1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(clientInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        bookingInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Booking Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Homestead Display", 0, 24))); // NOI18N
        bookingInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailAddress_Label2.setFont(new java.awt.Font("Ribbon", 0, 18)); // NOI18N
        emailAddress_Label2.setText("Where would you have your Photoshoot?");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/images.jpg"))); // NOI18N
        jButton1.setText("Studio");
        jButton1.setBorderPainted(false);
        jButton1.setOpaque(false);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/HawthornePark.jpg"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);

        jLabel4.setFont(new java.awt.Font("Ribbon", 0, 14)); // NOI18N
        jLabel4.setText("Studio");

        jLabel5.setFont(new java.awt.Font("Ribbon", 0, 14)); // NOI18N
        jLabel5.setText("Other Locations?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout whereChoice_PaneLayout = new javax.swing.GroupLayout(whereChoice_Pane);
        whereChoice_Pane.setLayout(whereChoice_PaneLayout);
        whereChoice_PaneLayout.setHorizontalGroup(
            whereChoice_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(whereChoice_PaneLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(whereChoice_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailAddress_Label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(whereChoice_PaneLayout.createSequentialGroup()
                        .addGroup(whereChoice_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addGroup(whereChoice_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(928, 928, 928))
        );
        whereChoice_PaneLayout.setVerticalGroup(
            whereChoice_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(whereChoice_PaneLayout.createSequentialGroup()
                .addGroup(whereChoice_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(whereChoice_PaneLayout.createSequentialGroup()
                        .addComponent(emailAddress_Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(whereChoice_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(whereChoice_PaneLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, whereChoice_PaneLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bookingInfo.add(whereChoice_Pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 32, 463, -1));

        emailAddress_Label4.setFont(new java.awt.Font("Ribbon", 0, 18)); // NOI18N
        emailAddress_Label4.setText("Where would you have your Photoshoot?");

        javax.swing.GroupLayout studio_ChoiceLayout = new javax.swing.GroupLayout(studio_Choice);
        studio_Choice.setLayout(studio_ChoiceLayout);
        studio_ChoiceLayout.setHorizontalGroup(
            studio_ChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(studio_ChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(studio_ChoiceLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(emailAddress_Label4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(269, Short.MAX_VALUE)))
        );
        studio_ChoiceLayout.setVerticalGroup(
            studio_ChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
            .addGroup(studio_ChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(studio_ChoiceLayout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addComponent(emailAddress_Label4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(91, Short.MAX_VALUE)))
        );

        bookingInfo.add(studio_Choice, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 34, 460, 210));

        cancelP_Button1.setText("Cancel");

        confirmP_Button1.setText("Confirm");
        confirmP_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmP_Button1ActionPerformed(evt);
            }
        });

        resetP_Button1.setText("Reset");

        javax.swing.GroupLayout addPG_Buttons1Layout = new javax.swing.GroupLayout(addPG_Buttons1);
        addPG_Buttons1.setLayout(addPG_Buttons1Layout);
        addPG_Buttons1Layout.setHorizontalGroup(
            addPG_Buttons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPG_Buttons1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetP_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(cancelP_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(addPG_Buttons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(addPG_Buttons1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(confirmP_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(353, Short.MAX_VALUE)))
        );
        addPG_Buttons1Layout.setVerticalGroup(
            addPG_Buttons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPG_Buttons1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPG_Buttons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelP_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetP_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(addPG_Buttons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(addPG_Buttons1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(confirmP_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout addPhotoshoot_FrameLayout = new javax.swing.GroupLayout(addPhotoshoot_Frame.getContentPane());
        addPhotoshoot_Frame.getContentPane().setLayout(addPhotoshoot_FrameLayout);
        addPhotoshoot_FrameLayout.setHorizontalGroup(
            addPhotoshoot_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clientInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookingInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addPG_Buttons1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addPhotoshoot_FrameLayout.setVerticalGroup(
            addPhotoshoot_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPhotoshoot_FrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clientInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(addPG_Buttons1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title2.setBackground(new java.awt.Color(255, 255, 255));
        title2.setFont(new java.awt.Font("Homestead Display", 0, 48)); // NOI18N
        title2.setForeground(new java.awt.Color(153, 153, 153));
        title2.setText("Photographers");
        adminPane.add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 320, 60));

        addPhotoGrapher_Button.setBackground(new java.awt.Color(51, 102, 255));
        addPhotoGrapher_Button.setFont(new java.awt.Font("Homestead Display", 0, 11)); // NOI18N
        addPhotoGrapher_Button.setForeground(new java.awt.Color(204, 204, 204));
        addPhotoGrapher_Button.setText("Add Photographer");
        addPhotoGrapher_Button.setBorderPainted(false);
        addPhotoGrapher_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPhotoGrapher_ButtonActionPerformed(evt);
            }
        });
        adminPane.add(addPhotoGrapher_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 180, 56));

        editPhotoGrapher_Button1.setBackground(new java.awt.Color(51, 102, 255));
        editPhotoGrapher_Button1.setFont(new java.awt.Font("Homestead Display", 0, 11)); // NOI18N
        editPhotoGrapher_Button1.setForeground(new java.awt.Color(204, 204, 204));
        editPhotoGrapher_Button1.setText("Edit Photographer");
        editPhotoGrapher_Button1.setBorderPainted(false);
        editPhotoGrapher_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPhotoGrapher_Button1ActionPerformed(evt);
            }
        });
        adminPane.add(editPhotoGrapher_Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 180, 56));

        removePG_Button.setBackground(new java.awt.Color(51, 102, 255));
        removePG_Button.setFont(new java.awt.Font("Homestead Display", 0, 11)); // NOI18N
        removePG_Button.setForeground(new java.awt.Color(204, 204, 204));
        removePG_Button.setText("Remove Photographer");
        removePG_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePG_ButtonActionPerformed(evt);
            }
        });
        adminPane.add(removePG_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 180, 63));

        ViewPhotographerSchedule.setBackground(new java.awt.Color(51, 102, 255));
        ViewPhotographerSchedule.setFont(new java.awt.Font("Homestead Display", 0, 11)); // NOI18N
        ViewPhotographerSchedule.setForeground(new java.awt.Color(204, 204, 204));
        ViewPhotographerSchedule.setText("View Photographer Schedule");
        ViewPhotographerSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPhotographerScheduleActionPerformed(evt);
            }
        });
        adminPane.add(ViewPhotographerSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 180, 61));

        toGuest_Button.setBackground(new java.awt.Color(51, 102, 255));
        toGuest_Button.setFont(new java.awt.Font("Homestead Display", 0, 11)); // NOI18N
        toGuest_Button.setForeground(new java.awt.Color(204, 204, 204));
        toGuest_Button.setText("Change to Client Pane");
        toGuest_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toGuest_ButtonActionPerformed(evt);
            }
        });
        adminPane.add(toGuest_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        Services_Button.setBackground(new java.awt.Color(51, 102, 255));
        Services_Button.setFont(new java.awt.Font("Homestead Display", 0, 11)); // NOI18N
        Services_Button.setForeground(new java.awt.Color(204, 204, 204));
        Services_Button.setText("Services");
        Services_Button.setBorderPainted(false);
        Services_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Services_ButtonActionPerformed(evt);
            }
        });
        adminPane.add(Services_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 180, 56));

        Clients.setBackground(new java.awt.Color(51, 102, 255));
        Clients.setFont(new java.awt.Font("Homestead Display", 0, 11)); // NOI18N
        Clients.setForeground(new java.awt.Color(204, 204, 204));
        Clients.setText("Clients");
        Clients.setBorderPainted(false);
        Clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientsActionPerformed(evt);
            }
        });
        adminPane.add(Clients, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 180, 56));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/Backgrounds.jpg"))); // NOI18N
        adminPane.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, -1));

        clientPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title3.setBackground(new java.awt.Color(255, 255, 255));
        title3.setFont(new java.awt.Font("Homestead Display", 0, 48)); // NOI18N
        title3.setForeground(new java.awt.Color(153, 153, 153));
        title3.setText("Liz' PhotoStudio");
        clientPane.add(title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 430, 60));

        bookButton.setBackground(new java.awt.Color(51, 102, 255));
        bookButton.setFont(new java.awt.Font("Ribbon", 0, 14)); // NOI18N
        bookButton.setForeground(new java.awt.Color(204, 204, 204));
        bookButton.setText("Book a PhotoShoot");
        bookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButtonActionPerformed(evt);
            }
        });
        clientPane.add(bookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 110, 260, 56));

        toAdminButton.setBackground(new java.awt.Color(51, 102, 255));
        toAdminButton.setFont(new java.awt.Font("Ribbon", 0, 11)); // NOI18N
        toAdminButton.setForeground(new java.awt.Color(204, 204, 204));
        toAdminButton.setText("Change to Admin Pane");
        toAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toAdminButtonActionPerformed(evt);
            }
        });
        clientPane.add(toAdminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        checkPhotoGButton.setBackground(new java.awt.Color(51, 102, 255));
        checkPhotoGButton.setFont(new java.awt.Font("Ribbon", 0, 14)); // NOI18N
        checkPhotoGButton.setForeground(new java.awt.Color(204, 204, 204));
        checkPhotoGButton.setText("Available Photographers");
        checkPhotoGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPhotoGButtonActionPerformed(evt);
            }
        });
        clientPane.add(checkPhotoGButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 180, 260, 63));

        viewBrochureButton.setBackground(new java.awt.Color(51, 102, 255));
        viewBrochureButton.setFont(new java.awt.Font("Ribbon", 0, 14)); // NOI18N
        viewBrochureButton.setForeground(new java.awt.Color(204, 204, 204));
        viewBrochureButton.setText("View studio images");
        viewBrochureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBrochureButtonActionPerformed(evt);
            }
        });
        clientPane.add(viewBrochureButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 260, 260, 61));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/Backgrounds.jpg"))); // NOI18N
        clientPane.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clientPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(adminPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clientPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(adminPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButtonActionPerformed
        //new AddClientnoConstraint().setVisible(true);
        new EditClient().setVisible(true);
    }//GEN-LAST:event_bookButtonActionPerformed

    private void addPhotoGrapher_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPhotoGrapher_ButtonActionPerformed
        new addPhotographer_Frame().setVisible(true);
    }//GEN-LAST:event_addPhotoGrapher_ButtonActionPerformed

    private void toAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toAdminButtonActionPerformed
        clientPane.setVisible(false);
        adminPane.setVisible(true);
    }//GEN-LAST:event_toAdminButtonActionPerformed

    private void removePG_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePG_ButtonActionPerformed
        new removePhotographer().setVisible(true);
    }//GEN-LAST:event_removePG_ButtonActionPerformed

    private void confirmP_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmP_Button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmP_Button1ActionPerformed

    private void toGuest_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toGuest_ButtonActionPerformed
        // TODO add your handling code here:
        clientPane.setVisible(true);
        adminPane.setVisible(false);
    }//GEN-LAST:event_toGuest_ButtonActionPerformed

    private void editPhotoGrapher_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPhotoGrapher_Button1ActionPerformed
        // TODO add your handling code here:
        new EditPhotographer().setVisible(true);
    }//GEN-LAST:event_editPhotoGrapher_Button1ActionPerformed

    private void checkPhotoGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPhotoGButtonActionPerformed
        // TODO add your handling code here:
        new PhotographerAvailability().setVisible(true);
    }//GEN-LAST:event_checkPhotoGButtonActionPerformed

    private void ViewPhotographerScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPhotographerScheduleActionPerformed
        // TODO add your handling code here:
        new Report_Menu().setVisible(true);
    }//GEN-LAST:event_ViewPhotographerScheduleActionPerformed

    private void viewBrochureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBrochureButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewBrochureButtonActionPerformed

    private void Services_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Services_ButtonActionPerformed
        // TODO add your handling code here:
        new ViewServices().setVisible(true);
    }//GEN-LAST:event_Services_ButtonActionPerformed

    private void ClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientsActionPerformed
        // TODO add your handling code here:
        new EditClient().setVisible(true);
    }//GEN-LAST:event_ClientsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPane().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clients;
    private javax.swing.JButton Services_Button;
    private javax.swing.JButton ViewPhotographerSchedule;
    private javax.swing.JPanel addPG_Buttons1;
    private javax.swing.JButton addPhotoGrapher_Button;
    private javax.swing.JFrame addPhotoshoot_Frame;
    private javax.swing.JPanel adminPane;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JButton bookButton;
    private javax.swing.JPanel bookingInfo;
    private javax.swing.JButton cancelP_Button1;
    private javax.swing.JButton checkPhotoGButton;
    private javax.swing.JPanel clientInfo;
    private javax.swing.JPanel clientPane;
    private javax.swing.JButton confirmP_Button1;
    private javax.swing.JTextField contactNumber_Input1;
    private javax.swing.JLabel contactNumber_Label1;
    private javax.swing.JButton editPhotoGrapher_Button1;
    private javax.swing.JTextField emailAddress_Input1;
    private javax.swing.JLabel emailAddress_Label1;
    private javax.swing.JLabel emailAddress_Label2;
    private javax.swing.JLabel emailAddress_Label4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField name_Input1;
    private javax.swing.JTextField name_Input2;
    private javax.swing.JLabel name_Label1;
    private javax.swing.JLabel name_Label2;
    private javax.swing.JButton removePG_Button;
    private javax.swing.JButton resetP_Button1;
    private javax.swing.JPanel studio_Choice;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    private javax.swing.JButton toAdminButton;
    private javax.swing.JButton toGuest_Button;
    private javax.swing.JButton viewBrochureButton;
    private javax.swing.JPanel whereChoice_Pane;
    // End of variables declaration//GEN-END:variables
}
