/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Photographer;

import ORM.Photographer;
import ORM_Controller.Photographer_Controller;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author El Gato
 */
public class removePhotographer extends javax.swing.JFrame {
    private DefaultTableModel model;
    private Photographer_Controller pc;
    private Photographer p;
    private Integer key;
    private Integer index;
    /**
     * Creates new form removePhotographer
     */
    public removePhotographer() {
        pc = new Photographer_Controller();
        p = new Photographer();
        model = new DefaultTableModel();
        initializeModel();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable(){
            public boolean isCellEditable(int row,int column){
                return false;
            }
        };
        remove = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(model);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 580, 250));

        remove.setFont(new java.awt.Font("Homestead Regular", 0, 18)); // NOI18N
        remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/football.png"))); // NOI18N
        remove.setText("Remove");
        remove.setContentAreaFilled(false);
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        getContentPane().add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 200, 50));

        jLabel6.setFont(new java.awt.Font("Ribbon", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Remove Photographer");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg-2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
        pc.deletePhotographer(key);
        model.removeRow(index);
    }//GEN-LAST:event_removeActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        key = Integer.valueOf(String.valueOf(model.getValueAt(table.getSelectedRow(),0)));
        index = table.getSelectedRow();
    }//GEN-LAST:event_tableMouseClicked
    
    private void initializeModel(){
        Photographer_Controller pc = new Photographer_Controller();
        model.addColumn("PID");
        model.addColumn("Last Name");
        model.addColumn("First Name");
        model.addColumn("Employment Status");
        model.addColumn("Email");
        model.addColumn("Contact Number");
        
        ArrayList<Photographer> arr = new ArrayList<Photographer>(pc.viewAllPhotographers());
        for(Photographer p_tuple:arr){
            Object[] insert = {p_tuple.getPId(),p_tuple.getPLastname(),p_tuple.getPFirstname(),p_tuple.getEmploymentStatus(),p_tuple.getPEmailAd(),p_tuple.getPContactNumber()};
            model.addRow(insert);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton remove;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
