/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Photographer;

import ORM.Photographer;
import ORM_Controller.Photographer_Controller;
import handlers.InputMatcher;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class UpdatePhotographer extends javax.swing.JFrame {

    /**
     * Creates new form addPhotographer_Frame
     */
    private String lname, fname, cnum, email, other_c;
    private Photographer p;
    private Photographer_Controller pc;
    private Integer index;
    private Integer key;
    private EditPhotographer parent;

    public UpdatePhotographer() {
        initComponents();
    }

    public UpdatePhotographer(Photographer _p, Integer _key, Integer _index, EditPhotographer _parent) {

        pc = new Photographer_Controller();
        p = _p;
        index = _index;
        key = _key;
        parent = _parent;

        initComponents();
        setValuesToPhotographers();

    }

    private void setValuesToPhotographers() {
        last_name_Input.setText(p.getPLastname());

        first_name_Input1.setText(p.getPFirstname());
        contactNumber_Input.setText(p.getPContactNumber());
        emailAddress_Input.setText(p.getPEmailAd());

        if (p.getEmploymentStatus().equals("Freelance")) {
            freelance_RadioB.setSelected(true);
            other_c = "Freelance";
        } else if (p.getEmploymentStatus().equals("Regular")) {
            regular_RadioB.setSelected(true);
            other_c = "Regular";
        } else {
            otherStatus_Input.setText(p.getEmploymentStatus());
            other_radioB.setSelected(true);
            other_c = otherStatus_Input.getText();
        }

        lname = p.getPLastname();
        fname = p.getPFirstname();
        cnum = p.getPContactNumber();
        email = p.getPEmailAd();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basicInfo = new javax.swing.JPanel();
        name_Label = new javax.swing.JLabel();
        last_name_Input = new javax.swing.JTextField();
        contactNumber_Label = new javax.swing.JLabel();
        contactNumber_Input = new javax.swing.JTextField();
        emailAddress_Label = new javax.swing.JLabel();
        emailAddress_Input = new javax.swing.JTextField();
        name_Label1 = new javax.swing.JLabel();
        first_name_Input1 = new javax.swing.JTextField();
        check_changeLastName = new javax.swing.JCheckBox();
        check_changeFirstName = new javax.swing.JCheckBox();
        check_changeCnum = new javax.swing.JCheckBox();
        check_Changeemail = new javax.swing.JCheckBox();
        otherInfo = new javax.swing.JPanel();
        status_Label = new javax.swing.JLabel();
        regular_RadioB = new javax.swing.JRadioButton();
        freelance_RadioB = new javax.swing.JRadioButton();
        other_radioB = new javax.swing.JRadioButton();
        otherStatus_Input = new javax.swing.JTextField();
        check_Changestatus = new javax.swing.JCheckBox();
        addPG_Buttons = new javax.swing.JPanel();
        cancelP_Button = new javax.swing.JButton();
        confirmP_Button = new javax.swing.JButton();
        resetP_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        basicInfo.setBackground(new java.awt.Color(0, 102, 204));
        basicInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Basic Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        name_Label.setFont(new java.awt.Font("Homestead Display", 0, 18)); // NOI18N
        name_Label.setText("Last Name");

        last_name_Input.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        last_name_Input.setEnabled(false);

        contactNumber_Label.setFont(new java.awt.Font("Homestead Display", 0, 18)); // NOI18N
        contactNumber_Label.setText("Contact Number");

        contactNumber_Input.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        contactNumber_Input.setEnabled(false);

        emailAddress_Label.setFont(new java.awt.Font("Homestead Display", 0, 18)); // NOI18N
        emailAddress_Label.setText("Email Address");

        emailAddress_Input.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        emailAddress_Input.setEnabled(false);

        name_Label1.setFont(new java.awt.Font("Homestead Display", 0, 18)); // NOI18N
        name_Label1.setText("First Name");

        first_name_Input1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        first_name_Input1.setEnabled(false);

        check_changeLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_changeLastNameActionPerformed(evt);
            }
        });

        check_changeFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_changeFirstNameActionPerformed(evt);
            }
        });

        check_changeCnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_changeCnumActionPerformed(evt);
            }
        });

        check_Changeemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_ChangeemailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout basicInfoLayout = new javax.swing.GroupLayout(basicInfo);
        basicInfo.setLayout(basicInfoLayout);
        basicInfoLayout.setHorizontalGroup(
            basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(check_changeLastName)
                            .addComponent(check_changeFirstName))
                        .addComponent(check_changeCnum))
                    .addComponent(check_Changeemail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basicInfoLayout.createSequentialGroup()
                        .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(last_name_Input)
                            .addComponent(first_name_Input1)))
                    .addGroup(basicInfoLayout.createSequentialGroup()
                        .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailAddress_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactNumber_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contactNumber_Input, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(emailAddress_Input))))
                .addContainerGap())
        );
        basicInfoLayout.setVerticalGroup(
            basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(check_changeLastName)
                    .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(last_name_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(name_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(first_name_Input1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(name_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(check_changeFirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(contactNumber_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(contactNumber_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(check_changeCnum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emailAddress_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(emailAddress_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(check_Changeemail))
                .addContainerGap())
        );

        getContentPane().add(basicInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 470, 190));

        otherInfo.setBackground(new java.awt.Color(0, 102, 153));
        otherInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Other Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        status_Label.setFont(new java.awt.Font("Homestead Display", 0, 18)); // NOI18N
        status_Label.setText("Employment Status");

        regular_RadioB.setFont(new java.awt.Font("Ribbon", 0, 18)); // NOI18N
        regular_RadioB.setText("Regular");
        regular_RadioB.setEnabled(false);
        regular_RadioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regular_RadioBActionPerformed(evt);
            }
        });

        freelance_RadioB.setFont(new java.awt.Font("Ribbon", 0, 18)); // NOI18N
        freelance_RadioB.setText("Freelance");
        freelance_RadioB.setEnabled(false);
        freelance_RadioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freelance_RadioBActionPerformed(evt);
            }
        });

        other_radioB.setFont(new java.awt.Font("Ribbon", 0, 18)); // NOI18N
        other_radioB.setText("other");
        other_radioB.setEnabled(false);
        other_radioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                other_radioBActionPerformed(evt);
            }
        });

        otherStatus_Input.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        otherStatus_Input.setEnabled(false);

        check_Changestatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_ChangestatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout otherInfoLayout = new javax.swing.GroupLayout(otherInfo);
        otherInfo.setLayout(otherInfoLayout);
        otherInfoLayout.setHorizontalGroup(
            otherInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(otherInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(otherStatus_Input)
                    .addGroup(otherInfoLayout.createSequentialGroup()
                        .addComponent(check_Changestatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(otherInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(status_Label)
                            .addGroup(otherInfoLayout.createSequentialGroup()
                                .addComponent(regular_RadioB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(freelance_RadioB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(other_radioB, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 110, Short.MAX_VALUE)))
                .addContainerGap())
        );
        otherInfoLayout.setVerticalGroup(
            otherInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherInfoLayout.createSequentialGroup()
                .addGroup(otherInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(status_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_Changestatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regular_RadioB)
                    .addComponent(freelance_RadioB)
                    .addComponent(other_radioB))
                .addGap(16, 16, 16)
                .addComponent(otherStatus_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(otherInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 470, 150));

        addPG_Buttons.setBackground(new java.awt.Color(0, 102, 102));

        cancelP_Button.setFont(new java.awt.Font("Homestead Display", 0, 14)); // NOI18N
        cancelP_Button.setText("Cancel");
        cancelP_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelP_ButtonActionPerformed(evt);
            }
        });

        confirmP_Button.setFont(new java.awt.Font("Homestead Display", 0, 14)); // NOI18N
        confirmP_Button.setText("Update");
        confirmP_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmP_ButtonActionPerformed(evt);
            }
        });

        resetP_Button.setFont(new java.awt.Font("Homestead Display", 0, 14)); // NOI18N
        resetP_Button.setText("Reset");
        resetP_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetP_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPG_ButtonsLayout = new javax.swing.GroupLayout(addPG_Buttons);
        addPG_Buttons.setLayout(addPG_ButtonsLayout);
        addPG_ButtonsLayout.setHorizontalGroup(
            addPG_ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPG_ButtonsLayout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(confirmP_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(resetP_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelP_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        addPG_ButtonsLayout.setVerticalGroup(
            addPG_ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPG_ButtonsLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(addPG_ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetP_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelP_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmP_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(addPG_Buttons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 470, 70));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Check the elements you want to change. only checked elements shall be updated");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/Backgrounds.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regular_RadioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regular_RadioBActionPerformed
        freelance_RadioB.setSelected(false);
        other_radioB.setSelected(false);
        otherStatus_Input.setEnabled(false);
    }//GEN-LAST:event_regular_RadioBActionPerformed

    private void freelance_RadioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freelance_RadioBActionPerformed
        other_radioB.setSelected(false);
        regular_RadioB.setSelected(false);
        otherStatus_Input.setEnabled(false);
    }//GEN-LAST:event_freelance_RadioBActionPerformed

    private void other_radioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_other_radioBActionPerformed
        freelance_RadioB.setSelected(false);
        regular_RadioB.setSelected(false);
        otherStatus_Input.setEnabled(true);
    }//GEN-LAST:event_other_radioBActionPerformed

    private void cancelP_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelP_ButtonActionPerformed
        this.dispose();
        resetP_ButtonActionPerformed(null);
    }//GEN-LAST:event_cancelP_ButtonActionPerformed

    private void confirmP_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmP_ButtonActionPerformed
        // TODO add your handling code here:

        boolean reg, free, other;

        if (check_changeLastName.isSelected()) {
            lname = last_name_Input.getText();
            if (lname.isEmpty()) {
                showInputMisMatchDialog();
                return;
            } else {
                p.setPLastname(lname);
            }
        }

        if (check_changeFirstName.isSelected()) {
            fname = first_name_Input1.getText();
            if (fname.isEmpty()) {
                showInputMisMatchDialog();
                return;
            } else {
                p.setPFirstname(fname);
            }
        }

        if (check_changeCnum.isSelected()) {
            cnum = contactNumber_Input.getText();
            if (InputMatcher.isContactNumber(cnum)) {
                System.out.println("cnum");
                return;
            } else {
                p.setPContactNumber(cnum);
            }
        }

        if (check_Changeemail.isSelected()) {
            email = emailAddress_Input.getText();
            if (!InputMatcher.isEmail(email)) {
                showInputMisMatchDialog();
                return;
            } else {
                p.setPEmailAd(email);
            }
        }

        if (check_Changestatus.isSelected()) {
            other_c = otherStatus_Input.getText();
            reg = regular_RadioB.isSelected();
            free = freelance_RadioB.isSelected();
            other = other_radioB.isSelected();

            if (reg == true) {
                other_c = "Regular";
                p.setEmploymentStatus(other_c);
            } else if (free == true) {
                other_c = "Freelance";
                p.setEmploymentStatus(other_c);
            } else if (other == true) {
                if (!other_c.isEmpty()) {
                    p.setEmploymentStatus(other_c);
                } else {
                    JOptionPane.showMessageDialog(null, "Fill out the information properly");
                    return;
                }
            }
        }

        Photographer s = pc.findDuplicate(p);

        pc.updateContactNumber(cnum, key);
        pc.updateEmploymentStatus(other_c, key);
        pc.updateFirstName(fname, key);
        pc.updateLastName(lname, key);
        pc.updateEmail(email, key);

        parent.model.setValueAt(lname, index, 1);
        parent.model.setValueAt(fname, index, 2);
        parent.model.setValueAt(other_c, index, 3);
        parent.model.setValueAt(email, index, 4);
        parent.model.setValueAt(cnum, index, 5);
        JOptionPane.showMessageDialog(null, "Photographer Edited");
        this.dispose();


    }//GEN-LAST:event_confirmP_ButtonActionPerformed

    private void resetP_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetP_ButtonActionPerformed
        other_radioB.setSelected(false);
        regular_RadioB.setSelected(false);
        freelance_RadioB.setSelected(false);
        otherStatus_Input.setEnabled(false);
        setValuesToPhotographers();
        check_Changeemail.setSelected(false);
        check_Changestatus.setSelected(false);
        check_changeCnum.setSelected(false);
        check_changeFirstName.setSelected(false);
        check_changeLastName.setSelected(false);
        last_name_Input.setEnabled(false);
        first_name_Input1.setEnabled(false);
        contactNumber_Input.setEnabled(false);
        emailAddress_Input.setEnabled(false);
        regular_RadioB.setEnabled(false);
        freelance_RadioB.setEnabled(false);
        other_radioB.setEnabled(false);
        otherStatus_Input.setEnabled(false);

    }//GEN-LAST:event_resetP_ButtonActionPerformed

    private void check_changeLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_changeLastNameActionPerformed
        // TODO add your handling code here:
        if (check_changeLastName.isSelected()) {
            last_name_Input.setEnabled(true);
        } else {
            last_name_Input.setEnabled(false);
        }
    }//GEN-LAST:event_check_changeLastNameActionPerformed

    private void check_changeFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_changeFirstNameActionPerformed
        // TODO add your handling code here:
        if (check_changeFirstName.isSelected()) {
            first_name_Input1.setEnabled(true);
        } else {
            first_name_Input1.setEnabled(false);
        }
    }//GEN-LAST:event_check_changeFirstNameActionPerformed

    private void check_changeCnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_changeCnumActionPerformed
        // TODO add your handling code here:
        if (check_changeCnum.isSelected()) {
            contactNumber_Input.setEnabled(true);
        } else {
            contactNumber_Input.setEnabled(false);
        }
    }//GEN-LAST:event_check_changeCnumActionPerformed

    private void check_ChangeemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_ChangeemailActionPerformed
        // TODO add your handling code here:
        if (check_Changeemail.isSelected()) {
            emailAddress_Input.setEnabled(true);
        } else {
            emailAddress_Input.setEnabled(false);
        }
    }//GEN-LAST:event_check_ChangeemailActionPerformed

    private void check_ChangestatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_ChangestatusActionPerformed
        // TODO add your handling code here:
        if (check_Changestatus.isSelected()) {
            regular_RadioB.setEnabled(true);
            freelance_RadioB.setEnabled(true);
            other_radioB.setEnabled(true);
        } else {
            regular_RadioB.setEnabled(false);
            freelance_RadioB.setEnabled(false);
            other_radioB.setEnabled(false);
        }
    }//GEN-LAST:event_check_ChangestatusActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addPG_Buttons;
    private javax.swing.JPanel basicInfo;
    private javax.swing.JButton cancelP_Button;
    private javax.swing.JCheckBox check_Changeemail;
    private javax.swing.JCheckBox check_Changestatus;
    private javax.swing.JCheckBox check_changeCnum;
    private javax.swing.JCheckBox check_changeFirstName;
    private javax.swing.JCheckBox check_changeLastName;
    private javax.swing.JButton confirmP_Button;
    private javax.swing.JTextField contactNumber_Input;
    private javax.swing.JLabel contactNumber_Label;
    private javax.swing.JTextField emailAddress_Input;
    private javax.swing.JLabel emailAddress_Label;
    private javax.swing.JTextField first_name_Input1;
    private javax.swing.JRadioButton freelance_RadioB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField last_name_Input;
    private javax.swing.JLabel name_Label;
    private javax.swing.JLabel name_Label1;
    private javax.swing.JPanel otherInfo;
    private javax.swing.JTextField otherStatus_Input;
    private javax.swing.JRadioButton other_radioB;
    private javax.swing.JRadioButton regular_RadioB;
    private javax.swing.JButton resetP_Button;
    private javax.swing.JLabel status_Label;
    // End of variables declaration//GEN-END:variables

    private void showInputMisMatchDialog() {
        JOptionPane.showMessageDialog(null, "Fill out the Information Properly");
    }

}
