/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import Booking.ClientBookings;
import ORM.Client;
import ORM_Controller.Client_Controller;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author El Gato
 */
public class EditClient extends javax.swing.JFrame {
    protected DefaultTableModel model;
    private Integer key, index;
    private final Client_Controller pc;
    private Client p;
    /**
     * Creates new form updatePhotographer
     */
    public EditClient() {
        pc = new Client_Controller();
        p = new Client();
        initializeModel();
        initComponents();
    }

    public Client getTheClient(){
        return p;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        edit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        DeleteClient = new javax.swing.JButton();
        AddClient = new javax.swing.JButton();
        ViewBookings = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(model);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 620, 240));

        edit.setText("Edit Profile");
        edit.setEnabled(false);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 130, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Our Clients");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        DeleteClient.setText("Delete Client");
        DeleteClient.setEnabled(false);
        DeleteClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteClientActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 120, 50));

        AddClient.setText("Add Client");
        AddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClientActionPerformed(evt);
            }
        });
        getContentPane().add(AddClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 100, 50));

        ViewBookings.setText("View Bookings");
        ViewBookings.setEnabled(false);
        ViewBookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBookingsActionPerformed(evt);
            }
        });
        getContentPane().add(ViewBookings, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 130, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        key = Integer.valueOf(String.valueOf(model.getValueAt(table.getSelectedRow(),0)));
        p = pc.findClient(key);
        index = table.getSelectedRow();
        edit.setEnabled(true);
        DeleteClient.setEnabled(true);
        ViewBookings.setEnabled(true);
    }//GEN-LAST:event_tableMouseClicked

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        //pc.updateP;
        new UpdateClient(p, key, index, this).setVisible(true);
        edit.setEnabled(false);
        //model.removeRow(index);
    }//GEN-LAST:event_editActionPerformed

    private void DeleteClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteClientActionPerformed
        // TODO add your handling code here:
        new Client_Controller().deleteClient(key);
        model.removeRow(index);
        
        //new BookOldClient(p, key, index).setVisible(true);
    }//GEN-LAST:event_DeleteClientActionPerformed

    private void AddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddClientActionPerformed
        // TODO add your handling code here:
        new AddClient(this, index).setVisible(true);
    }//GEN-LAST:event_AddClientActionPerformed

    private void ViewBookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBookingsActionPerformed
        // TODO add your handling code here:
        new ClientBookings(new Client_Controller().findClient(key), this).setVisible(true);
    }//GEN-LAST:event_ViewBookingsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddClient;
    private javax.swing.JButton DeleteClient;
    private javax.swing.JButton ViewBookings;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    private void initializeModel() {
        model = new DefaultTableModel();
        model.addColumn("CID");
        model.addColumn("LastName");
        model.addColumn("FirstName");
        model.addColumn("Client Type");
        model.addColumn("Email ad");
        model.addColumn("Contact Number");
        ArrayList<Client> arr = new ArrayList<Client>(pc.viewAllClients());
        for(Client p_tuple:arr){
            Object[] insert = {p_tuple.getCId(),p_tuple.getCLastname(),p_tuple.getCFirstname(),p_tuple.getClientType(),p_tuple.getCEmailAd(),p_tuple.getCContactNumber()};
            model.addRow(insert);
        }
    }
}
