/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import ORM.Client;
import ORM_Controller.Client_Controller;
import handlers.InputMatcher;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author El Gato
 */
public class UpdateClient extends javax.swing.JFrame {
    private DefaultComboBoxModel listmodel;
    private Client_Controller pc;
    private Client p;
    private Integer key, index;
    private EditClient aThis;
    /**
     * Creates new form AddClient
     */
    public UpdateClient() {
        setAvailableClientTypes();
        initComponents();
        setValuesfromClient();
        if(listmodel.getSize()==0)
            ListOfPossibleClientTypes.setEnabled(false);
        
        listmodel.addListDataListener(ListOfPossibleClientTypes);
    }

    public UpdateClient(Client _p, Integer _key, Integer _index, EditClient _aThis) {
        pc = new Client_Controller();
        p = _p;
        key = _key;
        index = _index;
        aThis = _aThis;
        
        setAvailableClientTypes();
        initComponents();
        setValuesfromClient();
        if(listmodel.getSize()==0)
            ListOfPossibleClientTypes.setEnabled(false);
        
        listmodel.addListDataListener(ListOfPossibleClientTypes);
        
   
    }

    private void setAvailableClientTypes(){
        
        ArrayList ar = new ArrayList(new Client_Controller().viewAllTypes());
        ar.add(0,"Individual");
        ar.add(0,"Corporate");
        listmodel = new DefaultComboBoxModel(ar.toArray());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Confirm = new javax.swing.JButton();
        ContactNumber_input = new javax.swing.JTextField();
        LastName_input = new javax.swing.JTextField();
        FirstName_input = new javax.swing.JTextField();
        EmailAd_input = new javax.swing.JTextField();
        ListOfPossibleClientTypes = new javax.swing.JComboBox();
        Other = new javax.swing.JRadioButton();
        OtherType_input = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        checkbox_contactnumber = new javax.swing.JCheckBox();
        checkbox_lastname = new javax.swing.JCheckBox();
        checkbox_firstname = new javax.swing.JCheckBox();
        checkbox_clienttype = new javax.swing.JCheckBox();
        checkbox_emailad = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Confirm.setText("Confirm");
        Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(Confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 90, 50));

        ContactNumber_input.setEnabled(false);
        getContentPane().add(ContactNumber_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 190, -1));

        LastName_input.setEnabled(false);
        getContentPane().add(LastName_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 190, -1));

        FirstName_input.setEnabled(false);
        getContentPane().add(FirstName_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 190, -1));

        EmailAd_input.setEnabled(false);
        getContentPane().add(EmailAd_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 190, -1));

        ListOfPossibleClientTypes.setModel(listmodel);
        ListOfPossibleClientTypes.setEnabled(false);
        getContentPane().add(ListOfPossibleClientTypes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 190, -1));

        Other.setText("Other");
        Other.setEnabled(false);
        Other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherActionPerformed(evt);
            }
        });
        getContentPane().add(Other, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        OtherType_input.setEnabled(false);
        getContentPane().add(OtherType_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 120, -1));

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 80, 50));

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 110, 50));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setText("Edit");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 80, 30));

        checkbox_contactnumber.setText("Contact Number:");
        checkbox_contactnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_contactnumberActionPerformed(evt);
            }
        });
        getContentPane().add(checkbox_contactnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        checkbox_lastname.setText("Last Name:");
        checkbox_lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_lastnameActionPerformed(evt);
            }
        });
        getContentPane().add(checkbox_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        checkbox_firstname.setText("First Name:");
        checkbox_firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_firstnameActionPerformed(evt);
            }
        });
        getContentPane().add(checkbox_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        checkbox_clienttype.setText("Client Type:");
        checkbox_clienttype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_clienttypeActionPerformed(evt);
            }
        });
        getContentPane().add(checkbox_clienttype, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        checkbox_emailad.setText("Email Address:");
        checkbox_emailad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_emailadActionPerformed(evt);
            }
        });
        getContentPane().add(checkbox_emailad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtherActionPerformed
        // TODO add your handling code here:
        if(Other.isSelected()){
            ListOfPossibleClientTypes.setEnabled(false);
            OtherType_input.setEnabled(true);
        }
        else{
            ListOfPossibleClientTypes.setEnabled(true);
            OtherType_input.setEnabled(false);
        }
    }//GEN-LAST:event_OtherActionPerformed

    private void ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmActionPerformed
        // TODO add your handling code here:
         boolean reg, free, other;

        if (checkbox_lastname.isSelected()) {
            p.setCLastname(LastName_input.getText());
            if (p.getCLastname().isEmpty()) {
                showInputMisMatchDialog();
                return;
            } 
        }

        if (checkbox_firstname.isSelected()) {
            p.setCFirstname(FirstName_input.getText());
            if (p.getCFirstname().isEmpty()) {
                showInputMisMatchDialog();
                return;
            }
        }

        if (checkbox_contactnumber.isSelected()) {
            p.setCContactNumber(ContactNumber_input.getText());
            if (InputMatcher.isContactNumber(p.getCContactNumber())) {
                return;
            }
        }

        if (checkbox_emailad.isSelected()) {
            p.setCEmailAd(EmailAd_input.getText());
            if (!InputMatcher.isEmail(p.getCEmailAd())) {
                showInputMisMatchDialog();
                return;
            }
        }

        if(Other.isSelected()){
            p.setClientType(OtherType_input.getText());
            if(p.getClientType().isEmpty()){
                showInputMisMatchDialog();
                return;
            }
        }
        else{
            p.setClientType(String.valueOf(ListOfPossibleClientTypes.getSelectedItem()));
        }

        

        pc.updateContactNumber(p.getCContactNumber(), key);
        pc.updateClientType(p.getClientType(), key);
        pc.updateClientFirstName(p.getCFirstname(), key);
        pc.updateClientLastName(p.getCLastname(), key);
        pc.updateClientEmail(p.getCEmailAd(), key);

        aThis.model.setValueAt(p.getCLastname(), index, 1);
        aThis.model.setValueAt(p.getCFirstname(), index, 2);
        aThis.model.setValueAt(p.getClientType(), index, 3);
        aThis.model.setValueAt(p.getCEmailAd(), index, 4);
        aThis.model.setValueAt(p.getCContactNumber(), index, 5);
        JOptionPane.showMessageDialog(null, "Client Edited");
        this.dispose();

        
    }//GEN-LAST:event_ConfirmActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ContactNumber_input.setText("");
        EmailAd_input.setText("");
        FirstName_input.setText("");
        LastName_input.setText("");
        OtherType_input.setText("");
        Other.setSelected(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void checkbox_lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_lastnameActionPerformed
        // TODO add your handling code here:
        if(checkbox_lastname.isSelected()){
            LastName_input.setEnabled(true);
        }
        else{
            LastName_input.setEnabled(false);
        }
    }//GEN-LAST:event_checkbox_lastnameActionPerformed

    private void checkbox_firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_firstnameActionPerformed
        // TODO add your handling code here:
        if(checkbox_firstname.isSelected()){
            FirstName_input.setEnabled(true);
        }
        else{
            FirstName_input.setEnabled(false);
        }
    }//GEN-LAST:event_checkbox_firstnameActionPerformed

    private void checkbox_clienttypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_clienttypeActionPerformed
        // TODO add your handling code here:
        if(checkbox_clienttype.isSelected()){
            ListOfPossibleClientTypes.setEnabled(true);
            Other.setEnabled(true);
        }
        else{
            ListOfPossibleClientTypes.setEnabled(false);
            Other.setEnabled(false);
            OtherType_input.setEnabled(false);
        }
    }//GEN-LAST:event_checkbox_clienttypeActionPerformed

    private void checkbox_emailadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_emailadActionPerformed
        // TODO add your handling code here:
        if(checkbox_emailad.isSelected()){
            EmailAd_input.setEnabled(true);
        }
        else{
            EmailAd_input.setEnabled(false);
        }
    }//GEN-LAST:event_checkbox_emailadActionPerformed

    private void checkbox_contactnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_contactnumberActionPerformed
        // TODO add your handling code here:
        if(checkbox_contactnumber.isSelected()){
            ContactNumber_input.setEnabled(true);
        }
        else{
            ContactNumber_input.setEnabled(false);
        }
    }//GEN-LAST:event_checkbox_contactnumberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirm;
    private javax.swing.JTextField ContactNumber_input;
    private javax.swing.JTextField EmailAd_input;
    private javax.swing.JTextField FirstName_input;
    private javax.swing.JTextField LastName_input;
    private javax.swing.JComboBox ListOfPossibleClientTypes;
    private javax.swing.JRadioButton Other;
    private javax.swing.JTextField OtherType_input;
    private javax.swing.JCheckBox checkbox_clienttype;
    private javax.swing.JCheckBox checkbox_contactnumber;
    private javax.swing.JCheckBox checkbox_emailad;
    private javax.swing.JCheckBox checkbox_firstname;
    private javax.swing.JCheckBox checkbox_lastname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    private void setValuesfromClient() {
        LastName_input.setText(p.getCLastname());
        FirstName_input.setText(p.getCFirstname());
        ListOfPossibleClientTypes.setSelectedItem(p.getClientType());
        EmailAd_input.setText(p.getCEmailAd());
        ContactNumber_input.setText(p.getCContactNumber());
    }

    private void showInputMisMatchDialog() {
        JOptionPane.showMessageDialog(null, "Please fill out properly");
    }
}
